name: github pages

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PUSH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Set Up
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install . -r requirements-dev.txt

      - name: Make Sphinx docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build/html
