name: github pages

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PUSH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Set Up
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install . -r requirements-dev.txt

      - name: Make Sphinx docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Init new repository in dist folder and commit generated files
        run: |
          cd docs/build/html/
          git init
          git remote add origin https://${{ secrets.PUSH_TOKEN }}@github.com/Xylambda/kalmankit
          git config --global --add safe.directory /github/workspace/docs/build/html
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        uses: github-actions-x/commit@v3.1
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
